import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"

const interHeading = Inter({subsets:['latin'],variable:'--font-heading'});

const geistMono = Geist_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});


export const metadata: Metadata = {
  title: "ShipFlow AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-mono", geistMono.variable, interHeading.variable)}>
      <body className={`${geistSans.variable} ${geistMono.variable} dark`}>
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
